# Generated by Django 6.0.6 on 2026-06-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recien_registrado',
            field=models.BooleanField(default=True),
        ),
    ]
